name: 'Robot Overlord'
description: 'Better CODEOWNERS for a better world'
author: 'squarethecircle'
inputs:
  github-token: # change this
    required: true
    description: 'Github secret token'
  org-name:
    description: 'Github org parent of approver groups'
  approvers-dir:
    description: 'path to directory containing approvers files'
runs:
  using: 'node12'
  main: 'dist/index.js'
